Repository 3daddict/stl-estimator-nodejs, pull requests merged in 2019-10, with the labels that each got.

#15 Materialize
  templates/views/contributors.hbs
  templates/views/index.hbs
  templates/views/style-guide.hbs
Labels: enhancement

#16 Dev
  templates/views/contributors.hbs
  templates/views/index.hbs
  templates/views/style-guide.hbs
Labels: deployment merge

#19 docs: fixes broken link, adds npm instructions
  README.md
Labels: Hacktoberfest, bug, improvements

#20 Documentation updates
  README.md
Labels: deployment merge

#22 feat: adds styling to contributors page, adds build:sass task
  package.json
  public/css/styles.css
  public/css/styles.scss
  templates/views/contributors.hbs
Labels: deployment merge

#24 Dev
  templates/views/style-guide.hbs
Labels: deployment merge

#25 Setup Webpack 4
  package.json
  public/index.html
  public/js/app.js
  src/app.js
  templates/views/contributors.hbs
  templates/views/home.hbs
  templates/views/index.hbs
  templates/views/style-guide.hbs
  webpack.config.js
Labels: Hacktoberfest, feature request
